/*
 * Variants represented by image urls
 * Urls can be base64 encoded 1x1 pngs to represent color
 */

const color = {
  Aluminium: 'aluminium.jpg',
  Sort:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/black.jpg',
  'Sort / sort glas':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/black.jpg',
  'Børstet krom':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/boerstet-krom.jpg',
  'Børstet rustfri stål':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/brushed_steel.jpg',
  Krom:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/chrome.jpg',
  Corestone:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/corestone.jpg',
  'Grå folie':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/graa-folie.jpg',
  'Hvid blank':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-blank.jpg',
  'Hvid højglans folie':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-hoejglans-folie.jpg',
  'Hvid marmor':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-marmor.jpg',
  'Hvid mat':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-mat.jpg',
  'Hvidlakeret i højglans':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvidlakeret-i-hoejglans.jpg',
  Hvidlakeret:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvidlakeret.jpg',
  'Mat grå folie':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/mat-graa.jpg',
  'Mat melamin i mokkafarve':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/mat-melamin-i-mokkafarve.jpg',
  'Melamin i lys træ-look':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/melamin-i-lys-træ-look.jpg',
  'Melamin i træ-look':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/melamin-i-træ-look.jpg',
  Mørkegrå:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/moerke-graa.jpg',
  'Nero sten blank':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/nero-sten-blank.jpg',
  'Nero sten mat':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/nero-sten-mat.jpg',
  Porcelæn:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/porcelaen.jpg',
  'Silkemat hvid melamin med egetraesliste':
    'silkemat-hvid-melamin-med-egetraesliste.jpg',
  'Silkemat hvid melamin med egetræslister':
    'silkemat-hvid-melamin-med-egetraesliste.jpg',
  'Silkemat hvid melamin':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/silkemat-hvid-melamin.jpg',
  Silver:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/silver.jpg',
  'Rustfri stål':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/stainless_steel.jpg',
  'Rustfri stål,':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/stainless_steel.jpg',
  'Rustfrit stål,':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/stainless_steel.jpg',
  'Rustfrit stål':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/stainless_steel.jpg',
  Stål:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/stainless_steel.jpg',
  Hvid:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-blank.jpg',
  'Hvid,':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/hvid-blank.jpg',
  'Velvet black':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/velvet-black.jpg',
  Grafit:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/grafit.jpg',
  Supersteel:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/supersteel.jpg',
  Fragranite:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/fragranite.jpg',
  Stållook:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/staallook.jpg',
  Spejl:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/spejl.jpg',
  '16ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH01_Circle.jpg',
  '16ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH02_Circle.jpg',
  '16ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH03_Circle.jpg',
  '16ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH04_Circle.jpg',
  '16ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH05_Circle.jpg',
  '16ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH06_Circle.jpg',
  '16ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH07_Circle.jpg',
  '16ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH08_Circle.jpg',
  '16ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH09_Circle.jpg',
  '16ESHTH10_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH10_Circle.jpg',
  '16ESHTH11_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH11_Circle.jpg',
  '16ESHTH12_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH12_Circle.jpg',
  '16ESHTH13_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH13_Circle.jpg',
  '16ESHTH14_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH14_Circle.jpg',
  '16ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/16ESHTH17_Circle.jpg',
  '21ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH01_Circle.jpg',
  '21ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH02_Circle.jpg',
  '21ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH03_Circle.jpg',
  '21ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH04_Circle.jpg',
  '21ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH05_Circle.jpg',
  '21ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH06_Circle.jpg',
  '21ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH07_Circle.jpg',
  '21ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH08_Circle.jpg',
  '21ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH09_Circle.jpg',
  '21ESHTH10_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH10_Circle.jpg',
  '21ESHTH11_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH11_Circle.jpg',
  '21ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/21ESHTH17_Circle.jpg',
  '25ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH01_Circle.jpg',
  '25ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH02_Circle.jpg',
  '25ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH03_Circle.jpg',
  '25ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH04_Circle.jpg',
  '25ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH05_Circle.jpg',
  '25ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH06_Circle.jpg',
  '25ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH07_Circle.jpg',
  '25ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH08_Circle.jpg',
  '25ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/25ESHTH17_Circle.jpg',
  '28ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH01_Circle.jpg',
  '28ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH02_Circle.jpg',
  '28ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH03_Circle.jpg',
  '28ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH04_Circle.jpg',
  '28ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH05_Circle.jpg',
  '28ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH06_Circle.jpg',
  '28ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH07_Circle.jpg',
  '28ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH08_Circle.jpg',
  '28ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH09_Circle.jpg',
  '28ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/28ESHTH17_Circle.jpg',
  '31ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH01_Circle.jpg',
  '31ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH02_Circle.jpg',
  '31ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH03_Circle.jpg',
  '31ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH04_Circle.jpg',
  '31ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH05_Circle.jpg',
  '31ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH06_Circle.jpg',
  '31ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH07_Circle.jpg',
  '31ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH09_Circle.jpg',
  '31ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/31ESHTH17_Circle.jpg',
  '40ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH01_Circle.jpg',
  '40ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH02_Circle.jpg',
  '40ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH03_Circle.jpg',
  '40ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH04_Circle.jpg',
  '40ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH05_Circle.jpg',
  '40ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH06_Circle.jpg',
  '40ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH07_Circle.jpg',
  '40ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH08_Circle.jpg',
  '40ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH09_Circle.jpg',
  '40ESHTH10_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH10_Circle.jpg',
  '40ESHTH17_Cirlcle':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/40ESHTH17_Cirlcle.jpg',
  '44ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH01_Circle.jpg',
  '44ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH02_Circle.jpg',
  '44ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH03_Circle.jpg',
  '44ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH04_Circle.jpg',
  '44ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH05_Circle.jpg',
  '44ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH06_Circle.jpg',
  '44ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH07_Circle.jpg',
  '44ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH08_Circle.jpg',
  '44ESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH09_Circle.jpg',
  '44ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/44ESHTH17_Circle.jpg',
  '45ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH01_Circle.jpg',
  '45ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH02_Circle.jpg',
  '45ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH03_Circle.jpg',
  '45ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH04_Circle.jpg',
  '45ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH05_Circle.jpg',
  '45ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH06_Circle.jpg',
  '45ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH07_Circle.jpg',
  '45ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH08_Circle.jpg',
  '45ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/45ESHTH17_Circle.jpg',
  '52ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH01_Circle.jpg',
  '52ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH02_Circle.jpg',
  '52ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH03_Circle.jpg',
  '52ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH04_Circle.jpg',
  '52ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH05_Circle.jpg',
  '52ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH06_Circle.jpg',
  '52ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH07_Circle.jpg',
  '52ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH08_Circle.jpg',
  '52ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/52ESHTH17_Circle.jpg',
  '53ESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH01_Circle.jpg',
  '53ESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH02_Circle.jpg',
  '53ESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH03_Circle.jpg',
  '53ESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH04_Circle.jpg',
  '53ESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH05_Circle.jpg',
  '53ESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH06_Circle.jpg',
  '53ESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH07_Circle.jpg',
  '53ESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH08_Circle.jpg',
  '53ESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/53ESHTH17_Circle.jpg',
  'KPESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH01_Circle.jpg',
  'KPESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH02_Circle.jpg',
  'KPESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH03_Circle.jpg',
  'KPESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH04_Circle.jpg',
  'KPESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH05_Circle.jpg',
  'KPESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH06_Circle.jpg',
  'KPESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH07_Circle.jpg',
  'KPESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH08_Circle.jpg',
  'KPESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH09_Circle.jpg',
  'KPESHTH10_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH10_Circle.jpg',
  'KPESHTH11_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH11_Circle.jpg',
  'KPESHTH12_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH12_Circle.jpg',
  'KPESHTH13_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH13_Circle.jpg',
  'KPESHTH14_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH14_Circle.jpg',
  'KPESHTH15_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH15_Circle.jpg',
  'KPESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/KPESHTH17_Circle.jpg',
  'MLESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH01_Circle.jpg',
  'MLESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH02_Circle.jpg',
  'MLESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH03_Circle.jpg',
  'MLESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH04_Circle.jpg',
  'MLESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH05_Circle.jpg',
  'MLESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH06_Circle.jpg',
  'MLESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH07_Circle.jpg',
  'MLESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH08_Circle.jpg',
  'MLESHTH09_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH09_Circle.jpg',
  'MLESHTH10_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH10_Circle.jpg',
  'MLESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/MLESHTH17_Circle.jpg',
  'RWESHTH01_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH01_Circle.png',
  'RWESHTH02_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH02_Circle.png',
  'RWESHTH03_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH03_Circle.png',
  'RWESHTH04_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH04_Circle.png',
  'RWESHTH05_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH05_Circle.png',
  'RWESHTH06_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH06_Circle.png',
  'RWESHTH07_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH07_Circle.png',
  'RWESHTH08_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH08_Circle.png',
  'RWESHTH17_Circle.png':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/RWESHTH17_Circle.png',
}

const material = {
  Hvid:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/white.jpg',
  Sort:
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/product-colors/black.jpg',
}

const width = {
  '100':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm100.png',
  '1000':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1000.png',
  '1020':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1020.png',
  '1032':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1032.png',
  '1036':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1036.png',
  '1180':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1180.png',
  '120':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm120.png',
  '1200':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1200.png',
  '1220':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1220.png',
  '1232':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1232.png',
  '1236':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1236.png',
  '1420':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1420.png',
  '1436':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1436.png',
  '160':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm160.png',
  '1600':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1600.png',
  '1620':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1620.png',
  '1632':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1632.png',
  '1636':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm1636.png',
  '400':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm400.png',
  '480':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm480.png',
  '500':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm500.png',
  '530':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm530.png',
  '534':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm534.png',
  '540':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm540.png',
  '600':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm600.png',
  '602':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm602.png',
  '620':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm620.png',
  '636':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm636.png',
  '704':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm704.png',
  '710':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm710.png',
  '730':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm730.png',
  '734':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm734.png',
  '750':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm750.png',
  '770':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm770.png',
  '78':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm78.png',
  '800':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm800.png',
  '812':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm812.png',
  '820':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm820.png',
  '832':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm832.png',
  '836':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm836.png',
  '880':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm880.png',
  '900':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm900.png',
  '912':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm912.png',
  '94':
    'https://res.cloudinary.com/dgg9enyjv/image/upload/w_200,h_200/v1/hthdk/VariantImages/size/mm94.png',
}

module.exports = {
  color,
  features: {
    width,
    material,
    product_color: color,
    material_primary: color,
  },
}
