module.exports = {
  breadcrumbs: true,
  wishlist: true,
  defaults: {
    display: {
      id: false,
      brand: true,
      price: true,
      price_prefix: false,
      price_suffix: false,
      compare_price: true,
      price_disclaimer: true,
      price_disclaimer_2: true,
      variants: false,
      filters: true,
      sorting: true,
      features: true,
      tabs: {
        description: true,
        technical_details: true,
        instructions: true,
      },
    },
    sorting: [
      {
        key: 'price',
        ascending: true,
        value: 'price_asc',
      },
      {
        key: 'price',
        ascending: false,
        value: 'price_desc',
      },
    ],
    features: ['depth', 'width', 'height'],
    filters: ['brand', 'color', 'subCategory'],
  },
  categories: {
    refrigerators: {
      filters: ['subCategory', 'brand', 'features.installation_type'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
        'frost_free',
        'energy_rating',
        'capacity',
        'd_ba',
        'installation_type',
      ],
    },
    hobs: {
      filters: ['subCategory', 'brand'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
      ],
    },
    microwaves: {
      filters: ['subCategory', 'brand'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
        'capacity',
        'grillfunction',
      ],
    },
    'washers-dryers': {
      filters: ['subCategory', 'brand'],
      features: [
        'product_color',
        'height',
        'width',
        'depth',
        'capacity',
        'max_centrifugation',
        'energy_rating',
        'd_ba',
        'd_ba_certification',
      ],
    },
    dishwashers: {
      filters: ['subCategory', 'brand'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
        'number_of_programmes',
        'energy_rating',
        'd_ba',
      ],
    },
    'wine-coolers': {
      filters: ['brand', 'features.height', 'features.capacity'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
        'energy_rating',
        'capacity',
        'd_ba',
        'installation_type',
        'frost_free',
      ],
    },
    sinks: {
      filters: ['brand', 'color', 'size', 'subCategory'],
      features: [
        'product_color',
        'depth',
        'sink_leftright',
        'sink_frontback',
        '1_stbowl_leftright',
        '1_stbowl_frontback',
        '1_stbowl_depth',
        '2_ndbowl_leftright',
        '2_ndbowl_frontback',
        '2_ndbowl_depth',
        'minimum_cabinet_size',
        'material',
      ],
    },
    taps: {
      filters: ['brand', 'features.dishwasheronoff'],
      features: [
        'product_color',
        'tapheight',
        'depth',
        'dishwasheronoff',
        'watersafe',
      ],
    },
    ovens: {
      filters: ['subCategory', 'brand', 'color'],
      features: [
        'product_color',
        'height',
        'measurement_builtin_height',
        'width',
        'measurement_builtin_width',
        'depth',
        'measurement_builtin_depth',
        'capacity',
        'energy_rating',
        'material',
      ],
      compare: {
        tag: 'new',
      },
    },
    hoods: {
      filters: ['brand'],
      features: [
        'product_color',
        'height',
        'width',
        'depth',
        'ventilation',
        'energy_rating',
        'd_ba',
        'capacity',
        'capacity_1',
        'measurement_builtin_height',
      ],
    },
  },
  emailConsent: true,
}
