module.exports = {
  breadcrumbs: true,
  wishlist: true,
  defaults: {
    display: {
      brand: true,
      id: true,
      price: true,
      price_prefix: false,
      price_suffix: false,
      compare_price: true,
      price_disclaimer: false,
      variants: false,
      filters: true,
      sorting: true,
      features: true,
      tabs: {
        description: true,
        technical_details: true,
        instructions: true,
      },
    },
    sorting: [
      {
        key: 'price',
        ascending: true,
        value: 'price_asc',
      },
      {
        key: 'price',
        ascending: false,
        value: 'price_desc',
      },
    ],
    filters: ['brand', 'color', 'subCategory'],
  },
  categories: {
    worktops: {
      filters: ['subCategory', 'color'],
      features: ['product_color'],
    },
    'knobs-handles': {
      filters: ['color', 'subCategory'],
      features: ['article_number', 'material', 'size', 'product_color'],
    },
    taps: {
      filters: ['brand', 'color'],
      features: ['product_color'],
    },
    sinks: {
      filters: ['brand', 'color'],
      features: ['minimum_cabinet_size', 'product_color'],
    },
    hobs: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'number_of_zones',
        'number_of_power_levels',
        'amp_requirement',
        'control_type',
        'frame',
        'width',
        'height',
        'depth',
        'power_output',
      ],
    },
    fans: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'material',
        'size',
        'lighting_type',
        'extraction_rate',
        'd_ba',
        'energy_rating',
      ],
    },
    refrigerators: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'contruction_type',
        'energy_rating',
        'energy_usage',
        'capacity',
        'width',
        'height',
        'depth',
        'd_ba',
      ],
    },
    ovens: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'width',
        'height',
        'depth',
        'number_of_functions',
        'capacity',
        'microwave_max',
        'number_of_power_levels',
      ],
    },
    dishwashers: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'installation',
        'width',
        'height',
        'depth',
        'number_of_programmes',
        'number_of_place_settings',
        'water_consumption',
        'energy_rating',
        'energy_usage_annual',
        'd_ba',
        'control_type',
      ],
    },
    microwaves: {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'product_color',
        'depth',
        'width',
        'height',
        'capacity',
        'microwave_max',
        'number_of_power_levels',
        'microwave_type',
      ],
    },
    'coffee-machines': {
      filters: ['brand', 'color'],
      features: ['depth', 'width', 'height', 'product_color'],
    },
    'wine-coolers': {
      filters: ['brand', 'color', 'subCategory'],
      features: [
        'depth',
        'width',
        'height',
        'capacity',
        'energy_rating',
        'product_color',
      ],
    },
  },
  emailConsent: false,
}
