module.exports = {
  breadcrumbs: true,
  wishlist: true,
  defaults: {
    display: {
      brand: true,
      id: true,
      price: true,
      price_prefix: false,
      price_suffix: false,
      compare_price: false,
      price_disclaimer: false,
      variants: false,
      bullets: true,
      filters: true,
      sorting: true,
      features: true,
      tabs: {
        description: true,
        technical_details: true,
        instructions: true,
      },
    },
    sorting: [
      {
        key: 'price',
        ascending: true,
        value: 'price_asc',
      },
      {
        key: 'price',
        ascending: false,
        value: 'price_desc',
      },
    ],

    filters: ['brand', 'color', 'subCategory'],
  },
  categories: {
    rangemaster: {
      features: [
        'capacity',
        'control_type',
        'depth',
        'energy_rating',
        'fuel_type',
        'height',
        'number_of_burners',
        'second_oven_capacity',
        'width',
        'size',
      ],
      filters: ['subCategory', 'features.model', 'color', 'features.width'],
    },
    hoods: {
      filters: ['subCategory', 'brand', 'size'],
      features: [
        'material',
        'number_of_speeds',
        'size',
        'lighting_type',
        'control_type',
        'energy_rating',
        'width',
        'height',
        'depth',
      ],
    },
    fans: {
      filters: ['subCategory', 'brand', 'size'],
      features: [
        'material',
        'number_of_speeds',
        'size',
        'lighting_type',
        'control_type',
        'energy_rating',
        'width',
        'height',
        'depth',
      ],
    },
    flooring: {
      filters: ['subCategory', 'brand'],
      features: [
        'length',
        'width',
        'thickness',
        'material',
        'suitable_for_underfloor_heating',
        'size',
      ],
    },
    hobs: {
      filters: ['subCategory', 'color', 'brand', 'size'],
      features: [
        'number_of_zones',
        'control_type',
        'burner_types',
        'size',
        'width',
        'depth',
      ],
    },
    innovations: {
      filters: ['innovation_type', 'height', 'width', 'depth'],
      features: ['innovation_type', 'height', 'width', 'depth'],
    },
    microwaves: {
      filters: ['brand'],
      features: ['width', 'height', 'depth', 'capacity', 'control_type'],
    },
    'washers-dryers': {
      filters: ['subCategory', 'brand'],
      features: [
        'height',
        'width',
        'depth',
        'energy_rating',
        'number_of_programmes',
        'water_consumption',
        'd_ba',
        'capacity',
        'rpm',
        'display_type',
        'size',
      ],
    },
    dishwashers: {
      filters: ['brand', 'size'],
      features: [
        'size',
        'installation',
        'width',
        'height',
        'depth',
        'number_of_programmes',
        'number_of_place_settings',
        'temperature_settings',
        'water_consumption',
        'energy_rating',
        'd_ba',
      ],
    },
    'coffee-machines': {
      filters: ['brand'],
      features: ['material', 'width', 'height', 'depth', 'water_capacity'],
    },
    'wine-coolers': {
      filters: ['color', 'size'],
      features: [
        'energy_rating',
        'energy_usage',
        'capacity',
        'bottle_capacity',
        'control_type',
        'number_of_temperature_zones',
        'width',
        'd_ba',
        'size',
      ],
    },
    sinks: {
      filters: ['subCategory', 'brand'],
      features: [
        'material',
        'bowl_size',
        'first_bowl_dimensions',
        'color',
        'sink_width',
        'sink_depth',
        'size',
      ],
    },
    'knobs-handles': {
      filters: [
        'drilling_width',
        'subCategory',
        'color',
        'feature_handle_type',
      ],
      features: ['handle_type', 'finish', 'drilling_width', 'length', 'height'],
    },
    taps: {
      filters: ['subCategory'],
      features: [
        'material',
        'valve_type',
        'spout_type',
        'finish',
        'reach',
        'height',
        'min_pressure',
        'size',
      ],
    },
    refrigerators: {
      filters: ['subCategory', 'brand'],
      features: ['energy_rating', 'energy_usage', 'capacity'],
    },
    ovens: {
      filters: ['subCategory', 'brand'],
      features: [
        'material',
        'width',
        'height',
        'depth',
        'number_of_functions',
        'capacity',
        'energy_rating',
        'control_type',
        'size',
      ],
    },
    lighting: {
      filters: ['subCategory'],
    },
  },
  myAccount: true,
  emailConsent: false,
}
